const countries = ["USA", "Canada", "Other"];
const states = {
  USA: [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "Other",
  ],
  Canada: ["AB", "BC", "MB", "NB", "NL", "NS", "ON", "PE", "QC", "SK"],
  Other: ["AS", "GU", "MP", "PR", "VI"],
};
const allStates = [...states.USA, ...states.Canada, ...states.Other];
const essayDivisions = ["Junior", "Senior", "Adult"];
const juniorFolktales = [
  "Folktale A",
  "Folktale B",
  "Folktale C",
  "Folktale D",
  "Folktale E",
  "Folktale F",
  "Folktale G",
  "Folktale H",
];

module.exports = {
  countries: countries,
  states: states,
  allStates: allStates,
  essayDivisions: essayDivisions,
  juniorFolktales: juniorFolktales,
};
