	<script>
		function expandNav() {
		    var x = document.getElementById("mobile-navbar");
		    if (x.className === "mobile-navbar") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-navbar";
		    }
		} 
		function expand02() {
		    var x = document.getElementById("mobile-12");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand03() {
		    var x = document.getElementById("mobile-13");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand04() {
		    var x = document.getElementById("mobile-14");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand05() {
		    var x = document.getElementById("mobile-15");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand06() {
		    var x = document.getElementById("mobile-16");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand07() {
		    var x = document.getElementById("mobile-17");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
		function expand08() {
		    var x = document.getElementById("mobile-18");
		    if (x.className === "mobile-m10") {
		        x.className += " expand";
		    } else {
		        x.className = "mobile-m10";
		    }
		} 
	</script>
</body>
